services:
  server:
    container_name: tg-bot-server
    image: ${REGISTRY_URL}/${IMAGE_NAME}:${VERSION}
    build:
      context: .
    env_file:
      - .env
    environment:
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN:?err}
    ports:
      - "9988:8080"
    depends_on:
      postgres:
        condition: service_healthy

