services:
  server:
    container_name: tg-video-downloader
    image: ghcr.io/${IMAGE_NAME}:${VERSION}
    build:
      context: .
    env_file:
      - .env
    environment:
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN:?err}
      METRICS_USERNAME: ${METRICS_USERNAME:?err}
      METRICS_PASSWORD: ${METRICS_PASSWORD:?err}
    ports:
      - "9988:9900"
