# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: main

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  GO_VERSION: '1.23.4'
  REGISTRY_URL: gitea.walsy.synology.me
  IMAGE_NAME: dah4uk/telegram-vpn-bot
  VERSION: 'v0.0.${{ github.run_number }}'
  CONTAINER_NAME: telegram-vpn-bot

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache-dependency-path: ./go.sum

      - name: Test
        run: go test -cover -v ./...

  build_docker:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Create .env
        run: |
          # Создаем или перезаписываем .env
          echo "# Auto-generated .env file" > .env
          
          for var in ${{ vars }}; do
            key=$(echo "$var" | cut -d= -f1)
            value=$(echo "$var" | cut -d= -f2-)
            echo "${key}=${value}" >> .env
          done
          
          # Добавляем переменные из secrets
          echo "Adding secrets..."
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env
          echo "API_TOKEN=${{ secrets.API_TOKEN }}" >> .env
          
          cat .env


      - name: Log in to Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY_URL }}
          username: ${{ vars.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: ./Dockerfile
          push: true
          tags: ${{ env.REGISTRY_URL }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}

  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    needs: build_docker

    steps:
      - name: Log in to Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY_URL }}
          username: ${{ vars.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Deploy container
        run: |
          echo "DOCKER_HOST=$DOCKER_HOST"
          
          echo "Pulling container with version ${{ env.VERSION }}..."
          docker pull ${{ env.REGISTRY_URL }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
          
          echo "Stopping container..."
          docker stop ${{ env.CONTAINER_NAME }} || true
          
          echo "Removing container..."
          docker rm ${{ env.CONTAINER_NAME }} || true
          
          echo "Running container with version ${{ env.VERSION }}..."
          docker run -d --name telegram-vpn-bot ${{ env.REGISTRY_URL }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
