# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: main

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      deploy_type:
        description: 'Тип деплоя'
        required: true
        type: choice
        options:
          - prod
          - stage
        default: 'prod'
      version:
        description: 'Версия для деплоя (оставьте пустым для latest)'
        required: false
        type: string

env:
  GO_VERSION: '1.24.2'
  REGISTRY_URL: gitea.walsy.synology.me
  IMAGE_NAME: dah4uk/telegram-vpn-bot
  VERSION: 'v0.0.${{ github.run_number }}'
  CONTAINER_NAME: telegram-vpn-bot

jobs:
  build_docker:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Log in to Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY_URL }}
          username: ${{ vars.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push with docker-compose
        run: |
          docker compose build
          docker compose push


  deploy:
    runs-on: ubuntu-latest
    needs: build_docker
    if: github.event_name == 'workflow_dispatch'

    steps:
      - name: Log in to Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY_URL }}
          username: ${{ vars.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}


      - name: Create .env file
        run: |
          cat << EOF > .env
          REGISTRY_URL=${{ env.REGISTRY_URL }}
          IMAGE_NAME=${{ env.IMAGE_NAME }}
          VERSION=${{ env.VERSION }}
          TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}
          POSTGRES_USER=${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB=${{ secrets.POSTGRES_DB }}
          EOF

      - name: Deploy with docker-compose
        env:
          DOCKER_HOST: ${{ secrets.DOCKER_HOST }}
        run: |
            echo "Stopping and removing existing containers..."
            docker compose down --remove-orphans || true

            echo "Pulling latest images..."
            docker compose pull

            echo "Starting services..."
            docker compose up -d
